services:
  - type: static
    name: dhi-test-tracking-app
    env: static
    region: frankfurt
    buildCommand: npm run build
    staticPublishPath: ./dist
    pullRequestPreviewsEnabled: false
    envVars:
      - key: VITE_API_URL
        value: https://dhi-test-tracking-api.fly.dev
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

databases:
  - name: dhi-test-tracking-db
    region: frankfurt
    plan: free
    databaseName: dhi_test_tracking
