import { Router } from 'express';
import authRouter from './auth.js';
import productsRouter from './products.js';
import projectsRouter from './projects.js';
import campaignsRouter from './campaigns.js';
import featuresRouter from './features.js';
import anomaliesRouter from './anomalies.js';
import tasksRouter from './tasks.js';
import teamsRouter from './teams.js';
import dashboardRouter from './dashboard.js';
import testCasesRouter from './test-cases.js';
import requirementsRouter from './requirements.js';
import watchPointsRouter from './watchPoints.js';
import testExecutionsRouter from './testExecutions.js';
import testScenariosRouter from './testScenarios.js';
import versionsRouter from './versions.js';
import incidentsRouter from './incidents.js';
import evidenceRouter from './evidence.js';
import dependenciesRouter from './dependencies.js';
import goLiveRouter from './goLive.js';
import referentialRulesRouter from './referentialRules.js';

const router = Router();

router.use('/auth', authRouter);
router.use('/products', productsRouter);
router.use('/projects', projectsRouter);
router.use('/campaigns', campaignsRouter);
router.use('/features', featuresRouter);
router.use('/anomalies', anomaliesRouter);
router.use('/tasks', tasksRouter);
router.use('/teams', teamsRouter);
router.use('/dashboard', dashboardRouter);
router.use('/test-cases', testCasesRouter);
router.use('/requirements', requirementsRouter);
router.use('/watch-points', watchPointsRouter);
router.use('/test-executions', testExecutionsRouter);
router.use('/test-scenarios', testScenariosRouter);
router.use('/versions', versionsRouter);
router.use('/incidents', incidentsRouter);
router.use('/evidence', evidenceRouter);
router.use('/dependencies', dependenciesRouter);
router.use('/go-live', goLiveRouter);
router.use('/referential-rules', referentialRulesRouter);

export default router;
