/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdministrationRouteImport } from './routes/administration'
import { Route as AlertesRouteImport } from './routes/alertes'
import { Route as AnomaliesRouteImport } from './routes/anomalies'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as CampagnesRouteImport } from './routes/campagnes'
import { Route as CouvertureRouteImport } from './routes/couverture'
import { Route as DashboardAdminRouteImport } from './routes/dashboard-admin'
import { Route as DashboardChefRouteImport } from './routes/dashboard-chef'
import { Route as DashboardDeveloppeurRouteImport } from './routes/dashboard-developpeur'
import { Route as DashboardTesteurRouteImport } from './routes/dashboard-testeur'
import { Route as ExigencesRouteImport } from './routes/exigences'
import { Route as FonctionnalitesRouteImport } from './routes/fonctionnalites'
import { Route as GoLiveRouteImport } from './routes/go-live'
import { Route as LoginRouteImport } from './routes/login'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as PointsASurveillerRouteImport } from './routes/points-a-surveiller'
import { Route as ProduitsRouteImport } from './routes/produits'
import { Route as ProjetsRouteImport } from './routes/projets'
import { Route as ReferentielsRouteImport } from './routes/referentiels'
import { Route as AdministrationAjouterUtilisateurRouteImport } from './routes/administration.ajouter-utilisateur'
import { Route as AnomaliesDefectIdRouteImport } from './routes/anomalies.$defectId'
import { Route as AnomaliesAjouterRouteImport } from './routes/anomalies.ajouter'
import { Route as CampagnesCampaignIdRouteImport } from './routes/campagnes.$campaignId'
import { Route as CampagnesAjouterRouteImport } from './routes/campagnes.ajouter'
import { Route as ExecutionTestIdRouteImport } from './routes/execution.$testId'
import { Route as ExigencesAjouterRouteImport } from './routes/exigences.ajouter'
import { Route as FonctionnalitesAjouterRouteImport } from './routes/fonctionnalites.ajouter'
import { Route as PointsASurveillerAjouterRouteImport } from './routes/points-a-surveiller.ajouter'
import { Route as ProduitsProductIdRouteImport } from './routes/produits.$productId'
import { Route as ProduitsAjouterRouteImport } from './routes/produits.ajouter'
import { Route as ProjetsProjectIdRouteImport } from './routes/projets.$projectId'
import { Route as ProjetsAjouterRouteImport } from './routes/projets.ajouter'
import { Route as CampagnesCampaignIdImporterRouteImport } from './routes/campagnes.$campaignId.importer'
import { Route as ExigencesRequirementIdModifierRouteImport } from './routes/exigences.$requirementId.modifier'
import { Route as FonctionnalitesFeatureIdModifierRouteImport } from './routes/fonctionnalites.$featureId.modifier'
import { Route as ProduitsProductIdModifierRouteImport } from './routes/produits.$productId.modifier'
import { Route as ProjetsProjectIdModifierRouteImport } from './routes/projets.$projectId.modifier'
import { Route as CampagnesCampaignIdTestsAjouterRouteImport } from './routes/campagnes.$campaignId.tests.ajouter'
import { Route as CampagnesCampaignIdTestsTestIdModifierRouteImport } from './routes/campagnes.$campaignId.tests.$testId.modifier'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdministrationRoute = AdministrationRouteImport.update({
  id: '/administration',
  path: '/administration',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertesRoute = AlertesRouteImport.update({
  id: '/alertes',
  path: '/alertes',
  getParentRoute: () => rootRouteImport,
} as any)
const AnomaliesRoute = AnomaliesRouteImport.update({
  id: '/anomalies',
  path: '/anomalies',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const CampagnesRoute = CampagnesRouteImport.update({
  id: '/campagnes',
  path: '/campagnes',
  getParentRoute: () => rootRouteImport,
} as any)
const CouvertureRoute = CouvertureRouteImport.update({
  id: '/couverture',
  path: '/couverture',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAdminRoute = DashboardAdminRouteImport.update({
  id: '/dashboard-admin',
  path: '/dashboard-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardChefRoute = DashboardChefRouteImport.update({
  id: '/dashboard-chef',
  path: '/dashboard-chef',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardDeveloppeurRoute = DashboardDeveloppeurRouteImport.update({
  id: '/dashboard-developpeur',
  path: '/dashboard-developpeur',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardTesteurRoute = DashboardTesteurRouteImport.update({
  id: '/dashboard-testeur',
  path: '/dashboard-testeur',
  getParentRoute: () => rootRouteImport,
} as any)
const ExigencesRoute = ExigencesRouteImport.update({
  id: '/exigences',
  path: '/exigences',
  getParentRoute: () => rootRouteImport,
} as any)
const FonctionnalitesRoute = FonctionnalitesRouteImport.update({
  id: '/fonctionnalites',
  path: '/fonctionnalites',
  getParentRoute: () => rootRouteImport,
} as any)
const GoLiveRoute = GoLiveRouteImport.update({
  id: '/go-live',
  path: '/go-live',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const PointsASurveillerRoute = PointsASurveillerRouteImport.update({
  id: '/points-a-surveiller',
  path: '/points-a-surveiller',
  getParentRoute: () => rootRouteImport,
} as any)
const ProduitsRoute = ProduitsRouteImport.update({
  id: '/produits',
  path: '/produits',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetsRoute = ProjetsRouteImport.update({
  id: '/projets',
  path: '/projets',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferentielsRoute = ReferentielsRouteImport.update({
  id: '/referentiels',
  path: '/referentiels',
  getParentRoute: () => rootRouteImport,
} as any)
const AdministrationAjouterUtilisateurRoute =
  AdministrationAjouterUtilisateurRouteImport.update({
    id: '/ajouter-utilisateur',
    path: '/ajouter-utilisateur',
    getParentRoute: () => AdministrationRoute,
  } as any)
const AnomaliesDefectIdRoute = AnomaliesDefectIdRouteImport.update({
  id: '/$defectId',
  path: '/$defectId',
  getParentRoute: () => AnomaliesRoute,
} as any)
const AnomaliesAjouterRoute = AnomaliesAjouterRouteImport.update({
  id: '/ajouter',
  path: '/ajouter',
  getParentRoute: () => AnomaliesRoute,
} as any)
const CampagnesCampaignIdRoute = CampagnesCampaignIdRouteImport.update({
  id: '/$campaignId',
  path: '/$campaignId',
  getParentRoute: () => CampagnesRoute,
} as any)
const CampagnesAjouterRoute = CampagnesAjouterRouteImport.update({
  id: '/ajouter',
  path: '/ajouter',
  getParentRoute: () => CampagnesRoute,
} as any)
const ExecutionTestIdRoute = ExecutionTestIdRouteImport.update({
  id: '/execution/$testId',
  path: '/execution/$testId',
  getParentRoute: () => rootRouteImport,
} as any)
const ExigencesAjouterRoute = ExigencesAjouterRouteImport.update({
  id: '/ajouter',
  path: '/ajouter',
  getParentRoute: () => ExigencesRoute,
} as any)
const FonctionnalitesAjouterRoute = FonctionnalitesAjouterRouteImport.update({
  id: '/ajouter',
  path: '/ajouter',
  getParentRoute: () => FonctionnalitesRoute,
} as any)
const PointsASurveillerAjouterRoute =
  PointsASurveillerAjouterRouteImport.update({
    id: '/ajouter',
    path: '/ajouter',
    getParentRoute: () => PointsASurveillerRoute,
  } as any)
const ProduitsProductIdRoute = ProduitsProductIdRouteImport.update({
  id: '/$productId',
  path: '/$productId',
  getParentRoute: () => ProduitsRoute,
} as any)
const ProduitsAjouterRoute = ProduitsAjouterRouteImport.update({
  id: '/ajouter',
  path: '/ajouter',
  getParentRoute: () => ProduitsRoute,
} as any)
const ProjetsProjectIdRoute = ProjetsProjectIdRouteImport.update({
  id: '/$projectId',
  path: '/$projectId',
  getParentRoute: () => ProjetsRoute,
} as any)
const ProjetsAjouterRoute = ProjetsAjouterRouteImport.update({
  id: '/ajouter',
  path: '/ajouter',
  getParentRoute: () => ProjetsRoute,
} as any)
const CampagnesCampaignIdImporterRoute =
  CampagnesCampaignIdImporterRouteImport.update({
    id: '/importer',
    path: '/importer',
    getParentRoute: () => CampagnesCampaignIdRoute,
  } as any)
const ExigencesRequirementIdModifierRoute =
  ExigencesRequirementIdModifierRouteImport.update({
    id: '/$requirementId/modifier',
    path: '/$requirementId/modifier',
    getParentRoute: () => ExigencesRoute,
  } as any)
const FonctionnalitesFeatureIdModifierRoute =
  FonctionnalitesFeatureIdModifierRouteImport.update({
    id: '/$featureId/modifier',
    path: '/$featureId/modifier',
    getParentRoute: () => FonctionnalitesRoute,
  } as any)
const ProduitsProductIdModifierRoute =
  ProduitsProductIdModifierRouteImport.update({
    id: '/modifier',
    path: '/modifier',
    getParentRoute: () => ProduitsProductIdRoute,
  } as any)
const ProjetsProjectIdModifierRoute =
  ProjetsProjectIdModifierRouteImport.update({
    id: '/modifier',
    path: '/modifier',
    getParentRoute: () => ProjetsProjectIdRoute,
  } as any)
const CampagnesCampaignIdTestsAjouterRoute =
  CampagnesCampaignIdTestsAjouterRouteImport.update({
    id: '/tests/ajouter',
    path: '/tests/ajouter',
    getParentRoute: () => CampagnesCampaignIdRoute,
  } as any)
const CampagnesCampaignIdTestsTestIdModifierRoute =
  CampagnesCampaignIdTestsTestIdModifierRouteImport.update({
    id: '/tests/$testId/modifier',
    path: '/tests/$testId/modifier',
    getParentRoute: () => CampagnesCampaignIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/administration': typeof AdministrationRouteWithChildren
  '/alertes': typeof AlertesRoute
  '/anomalies': typeof AnomaliesRouteWithChildren
  '/audit': typeof AuditRoute
  '/campagnes': typeof CampagnesRouteWithChildren
  '/couverture': typeof CouvertureRoute
  '/dashboard-admin': typeof DashboardAdminRoute
  '/dashboard-chef': typeof DashboardChefRoute
  '/dashboard-developpeur': typeof DashboardDeveloppeurRoute
  '/dashboard-testeur': typeof DashboardTesteurRoute
  '/exigences': typeof ExigencesRouteWithChildren
  '/fonctionnalites': typeof FonctionnalitesRouteWithChildren
  '/go-live': typeof GoLiveRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/points-a-surveiller': typeof PointsASurveillerRouteWithChildren
  '/produits': typeof ProduitsRouteWithChildren
  '/projets': typeof ProjetsRouteWithChildren
  '/referentiels': typeof ReferentielsRoute
  '/administration/ajouter-utilisateur': typeof AdministrationAjouterUtilisateurRoute
  '/anomalies/$defectId': typeof AnomaliesDefectIdRoute
  '/anomalies/ajouter': typeof AnomaliesAjouterRoute
  '/campagnes/$campaignId': typeof CampagnesCampaignIdRouteWithChildren
  '/campagnes/ajouter': typeof CampagnesAjouterRoute
  '/execution/$testId': typeof ExecutionTestIdRoute
  '/exigences/ajouter': typeof ExigencesAjouterRoute
  '/fonctionnalites/ajouter': typeof FonctionnalitesAjouterRoute
  '/points-a-surveiller/ajouter': typeof PointsASurveillerAjouterRoute
  '/produits/$productId': typeof ProduitsProductIdRouteWithChildren
  '/produits/ajouter': typeof ProduitsAjouterRoute
  '/projets/$projectId': typeof ProjetsProjectIdRouteWithChildren
  '/projets/ajouter': typeof ProjetsAjouterRoute
  '/campagnes/$campaignId/importer': typeof CampagnesCampaignIdImporterRoute
  '/exigences/$requirementId/modifier': typeof ExigencesRequirementIdModifierRoute
  '/fonctionnalites/$featureId/modifier': typeof FonctionnalitesFeatureIdModifierRoute
  '/produits/$productId/modifier': typeof ProduitsProductIdModifierRoute
  '/projets/$projectId/modifier': typeof ProjetsProjectIdModifierRoute
  '/campagnes/$campaignId/tests/ajouter': typeof CampagnesCampaignIdTestsAjouterRoute
  '/campagnes/$campaignId/tests/$testId/modifier': typeof CampagnesCampaignIdTestsTestIdModifierRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/administration': typeof AdministrationRouteWithChildren
  '/alertes': typeof AlertesRoute
  '/anomalies': typeof AnomaliesRouteWithChildren
  '/audit': typeof AuditRoute
  '/campagnes': typeof CampagnesRouteWithChildren
  '/couverture': typeof CouvertureRoute
  '/dashboard-admin': typeof DashboardAdminRoute
  '/dashboard-chef': typeof DashboardChefRoute
  '/dashboard-developpeur': typeof DashboardDeveloppeurRoute
  '/dashboard-testeur': typeof DashboardTesteurRoute
  '/exigences': typeof ExigencesRouteWithChildren
  '/fonctionnalites': typeof FonctionnalitesRouteWithChildren
  '/go-live': typeof GoLiveRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/points-a-surveiller': typeof PointsASurveillerRouteWithChildren
  '/produits': typeof ProduitsRouteWithChildren
  '/projets': typeof ProjetsRouteWithChildren
  '/referentiels': typeof ReferentielsRoute
  '/administration/ajouter-utilisateur': typeof AdministrationAjouterUtilisateurRoute
  '/anomalies/$defectId': typeof AnomaliesDefectIdRoute
  '/anomalies/ajouter': typeof AnomaliesAjouterRoute
  '/campagnes/$campaignId': typeof CampagnesCampaignIdRouteWithChildren
  '/campagnes/ajouter': typeof CampagnesAjouterRoute
  '/execution/$testId': typeof ExecutionTestIdRoute
  '/exigences/ajouter': typeof ExigencesAjouterRoute
  '/fonctionnalites/ajouter': typeof FonctionnalitesAjouterRoute
  '/points-a-surveiller/ajouter': typeof PointsASurveillerAjouterRoute
  '/produits/$productId': typeof ProduitsProductIdRouteWithChildren
  '/produits/ajouter': typeof ProduitsAjouterRoute
  '/projets/$projectId': typeof ProjetsProjectIdRouteWithChildren
  '/projets/ajouter': typeof ProjetsAjouterRoute
  '/campagnes/$campaignId/importer': typeof CampagnesCampaignIdImporterRoute
  '/exigences/$requirementId/modifier': typeof ExigencesRequirementIdModifierRoute
  '/fonctionnalites/$featureId/modifier': typeof FonctionnalitesFeatureIdModifierRoute
  '/produits/$productId/modifier': typeof ProduitsProductIdModifierRoute
  '/projets/$projectId/modifier': typeof ProjetsProjectIdModifierRoute
  '/campagnes/$campaignId/tests/ajouter': typeof CampagnesCampaignIdTestsAjouterRoute
  '/campagnes/$campaignId/tests/$testId/modifier': typeof CampagnesCampaignIdTestsTestIdModifierRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/administration': typeof AdministrationRouteWithChildren
  '/alertes': typeof AlertesRoute
  '/anomalies': typeof AnomaliesRouteWithChildren
  '/audit': typeof AuditRoute
  '/campagnes': typeof CampagnesRouteWithChildren
  '/couverture': typeof CouvertureRoute
  '/dashboard-admin': typeof DashboardAdminRoute
  '/dashboard-chef': typeof DashboardChefRoute
  '/dashboard-developpeur': typeof DashboardDeveloppeurRoute
  '/dashboard-testeur': typeof DashboardTesteurRoute
  '/exigences': typeof ExigencesRouteWithChildren
  '/fonctionnalites': typeof FonctionnalitesRouteWithChildren
  '/go-live': typeof GoLiveRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/points-a-surveiller': typeof PointsASurveillerRouteWithChildren
  '/produits': typeof ProduitsRouteWithChildren
  '/projets': typeof ProjetsRouteWithChildren
  '/referentiels': typeof ReferentielsRoute
  '/administration/ajouter-utilisateur': typeof AdministrationAjouterUtilisateurRoute
  '/anomalies/$defectId': typeof AnomaliesDefectIdRoute
  '/anomalies/ajouter': typeof AnomaliesAjouterRoute
  '/campagnes/$campaignId': typeof CampagnesCampaignIdRouteWithChildren
  '/campagnes/ajouter': typeof CampagnesAjouterRoute
  '/execution/$testId': typeof ExecutionTestIdRoute
  '/exigences/ajouter': typeof ExigencesAjouterRoute
  '/fonctionnalites/ajouter': typeof FonctionnalitesAjouterRoute
  '/points-a-surveiller/ajouter': typeof PointsASurveillerAjouterRoute
  '/produits/$productId': typeof ProduitsProductIdRouteWithChildren
  '/produits/ajouter': typeof ProduitsAjouterRoute
  '/projets/$projectId': typeof ProjetsProjectIdRouteWithChildren
  '/projets/ajouter': typeof ProjetsAjouterRoute
  '/campagnes/$campaignId/importer': typeof CampagnesCampaignIdImporterRoute
  '/exigences/$requirementId/modifier': typeof ExigencesRequirementIdModifierRoute
  '/fonctionnalites/$featureId/modifier': typeof FonctionnalitesFeatureIdModifierRoute
  '/produits/$productId/modifier': typeof ProduitsProductIdModifierRoute
  '/projets/$projectId/modifier': typeof ProjetsProjectIdModifierRoute
  '/campagnes/$campaignId/tests/ajouter': typeof CampagnesCampaignIdTestsAjouterRoute
  '/campagnes/$campaignId/tests/$testId/modifier': typeof CampagnesCampaignIdTestsTestIdModifierRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/administration'
    | '/alertes'
    | '/anomalies'
    | '/audit'
    | '/campagnes'
    | '/couverture'
    | '/dashboard-admin'
    | '/dashboard-chef'
    | '/dashboard-developpeur'
    | '/dashboard-testeur'
    | '/exigences'
    | '/fonctionnalites'
    | '/go-live'
    | '/login'
    | '/notifications'
    | '/points-a-surveiller'
    | '/produits'
    | '/projets'
    | '/referentiels'
    | '/administration/ajouter-utilisateur'
    | '/anomalies/$defectId'
    | '/anomalies/ajouter'
    | '/campagnes/$campaignId'
    | '/campagnes/ajouter'
    | '/execution/$testId'
    | '/exigences/ajouter'
    | '/fonctionnalites/ajouter'
    | '/points-a-surveiller/ajouter'
    | '/produits/$productId'
    | '/produits/ajouter'
    | '/projets/$projectId'
    | '/projets/ajouter'
    | '/campagnes/$campaignId/importer'
    | '/exigences/$requirementId/modifier'
    | '/fonctionnalites/$featureId/modifier'
    | '/produits/$productId/modifier'
    | '/projets/$projectId/modifier'
    | '/campagnes/$campaignId/tests/ajouter'
    | '/campagnes/$campaignId/tests/$testId/modifier'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/administration'
    | '/alertes'
    | '/anomalies'
    | '/audit'
    | '/campagnes'
    | '/couverture'
    | '/dashboard-admin'
    | '/dashboard-chef'
    | '/dashboard-developpeur'
    | '/dashboard-testeur'
    | '/exigences'
    | '/fonctionnalites'
    | '/go-live'
    | '/login'
    | '/notifications'
    | '/points-a-surveiller'
    | '/produits'
    | '/projets'
    | '/referentiels'
    | '/administration/ajouter-utilisateur'
    | '/anomalies/$defectId'
    | '/anomalies/ajouter'
    | '/campagnes/$campaignId'
    | '/campagnes/ajouter'
    | '/execution/$testId'
    | '/exigences/ajouter'
    | '/fonctionnalites/ajouter'
    | '/points-a-surveiller/ajouter'
    | '/produits/$productId'
    | '/produits/ajouter'
    | '/projets/$projectId'
    | '/projets/ajouter'
    | '/campagnes/$campaignId/importer'
    | '/exigences/$requirementId/modifier'
    | '/fonctionnalites/$featureId/modifier'
    | '/produits/$productId/modifier'
    | '/projets/$projectId/modifier'
    | '/campagnes/$campaignId/tests/ajouter'
    | '/campagnes/$campaignId/tests/$testId/modifier'
  id:
    | '__root__'
    | '/'
    | '/administration'
    | '/alertes'
    | '/anomalies'
    | '/audit'
    | '/campagnes'
    | '/couverture'
    | '/dashboard-admin'
    | '/dashboard-chef'
    | '/dashboard-developpeur'
    | '/dashboard-testeur'
    | '/exigences'
    | '/fonctionnalites'
    | '/go-live'
    | '/login'
    | '/notifications'
    | '/points-a-surveiller'
    | '/produits'
    | '/projets'
    | '/referentiels'
    | '/administration/ajouter-utilisateur'
    | '/anomalies/$defectId'
    | '/anomalies/ajouter'
    | '/campagnes/$campaignId'
    | '/campagnes/ajouter'
    | '/execution/$testId'
    | '/exigences/ajouter'
    | '/fonctionnalites/ajouter'
    | '/points-a-surveiller/ajouter'
    | '/produits/$productId'
    | '/produits/ajouter'
    | '/projets/$projectId'
    | '/projets/ajouter'
    | '/campagnes/$campaignId/importer'
    | '/exigences/$requirementId/modifier'
    | '/fonctionnalites/$featureId/modifier'
    | '/produits/$productId/modifier'
    | '/projets/$projectId/modifier'
    | '/campagnes/$campaignId/tests/ajouter'
    | '/campagnes/$campaignId/tests/$testId/modifier'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdministrationRoute: typeof AdministrationRouteWithChildren
  AlertesRoute: typeof AlertesRoute
  AnomaliesRoute: typeof AnomaliesRouteWithChildren
  AuditRoute: typeof AuditRoute
  CampagnesRoute: typeof CampagnesRouteWithChildren
  CouvertureRoute: typeof CouvertureRoute
  DashboardAdminRoute: typeof DashboardAdminRoute
  DashboardChefRoute: typeof DashboardChefRoute
  DashboardDeveloppeurRoute: typeof DashboardDeveloppeurRoute
  DashboardTesteurRoute: typeof DashboardTesteurRoute
  ExigencesRoute: typeof ExigencesRouteWithChildren
  FonctionnalitesRoute: typeof FonctionnalitesRouteWithChildren
  GoLiveRoute: typeof GoLiveRoute
  LoginRoute: typeof LoginRoute
  NotificationsRoute: typeof NotificationsRoute
  PointsASurveillerRoute: typeof PointsASurveillerRouteWithChildren
  ProduitsRoute: typeof ProduitsRouteWithChildren
  ProjetsRoute: typeof ProjetsRouteWithChildren
  ReferentielsRoute: typeof ReferentielsRoute
  ExecutionTestIdRoute: typeof ExecutionTestIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/administration': {
      id: '/administration'
      path: '/administration'
      fullPath: '/administration'
      preLoaderRoute: typeof AdministrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alertes': {
      id: '/alertes'
      path: '/alertes'
      fullPath: '/alertes'
      preLoaderRoute: typeof AlertesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anomalies': {
      id: '/anomalies'
      path: '/anomalies'
      fullPath: '/anomalies'
      preLoaderRoute: typeof AnomaliesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campagnes': {
      id: '/campagnes'
      path: '/campagnes'
      fullPath: '/campagnes'
      preLoaderRoute: typeof CampagnesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/couverture': {
      id: '/couverture'
      path: '/couverture'
      fullPath: '/couverture'
      preLoaderRoute: typeof CouvertureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard-admin': {
      id: '/dashboard-admin'
      path: '/dashboard-admin'
      fullPath: '/dashboard-admin'
      preLoaderRoute: typeof DashboardAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard-chef': {
      id: '/dashboard-chef'
      path: '/dashboard-chef'
      fullPath: '/dashboard-chef'
      preLoaderRoute: typeof DashboardChefRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard-developpeur': {
      id: '/dashboard-developpeur'
      path: '/dashboard-developpeur'
      fullPath: '/dashboard-developpeur'
      preLoaderRoute: typeof DashboardDeveloppeurRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard-testeur': {
      id: '/dashboard-testeur'
      path: '/dashboard-testeur'
      fullPath: '/dashboard-testeur'
      preLoaderRoute: typeof DashboardTesteurRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exigences': {
      id: '/exigences'
      path: '/exigences'
      fullPath: '/exigences'
      preLoaderRoute: typeof ExigencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fonctionnalites': {
      id: '/fonctionnalites'
      path: '/fonctionnalites'
      fullPath: '/fonctionnalites'
      preLoaderRoute: typeof FonctionnalitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/go-live': {
      id: '/go-live'
      path: '/go-live'
      fullPath: '/go-live'
      preLoaderRoute: typeof GoLiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/points-a-surveiller': {
      id: '/points-a-surveiller'
      path: '/points-a-surveiller'
      fullPath: '/points-a-surveiller'
      preLoaderRoute: typeof PointsASurveillerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produits': {
      id: '/produits'
      path: '/produits'
      fullPath: '/produits'
      preLoaderRoute: typeof ProduitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projets': {
      id: '/projets'
      path: '/projets'
      fullPath: '/projets'
      preLoaderRoute: typeof ProjetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/referentiels': {
      id: '/referentiels'
      path: '/referentiels'
      fullPath: '/referentiels'
      preLoaderRoute: typeof ReferentielsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/administration/ajouter-utilisateur': {
      id: '/administration/ajouter-utilisateur'
      path: '/ajouter-utilisateur'
      fullPath: '/administration/ajouter-utilisateur'
      preLoaderRoute: typeof AdministrationAjouterUtilisateurRouteImport
      parentRoute: typeof AdministrationRoute
    }
    '/anomalies/$defectId': {
      id: '/anomalies/$defectId'
      path: '/$defectId'
      fullPath: '/anomalies/$defectId'
      preLoaderRoute: typeof AnomaliesDefectIdRouteImport
      parentRoute: typeof AnomaliesRoute
    }
    '/anomalies/ajouter': {
      id: '/anomalies/ajouter'
      path: '/ajouter'
      fullPath: '/anomalies/ajouter'
      preLoaderRoute: typeof AnomaliesAjouterRouteImport
      parentRoute: typeof AnomaliesRoute
    }
    '/campagnes/$campaignId': {
      id: '/campagnes/$campaignId'
      path: '/$campaignId'
      fullPath: '/campagnes/$campaignId'
      preLoaderRoute: typeof CampagnesCampaignIdRouteImport
      parentRoute: typeof CampagnesRoute
    }
    '/campagnes/ajouter': {
      id: '/campagnes/ajouter'
      path: '/ajouter'
      fullPath: '/campagnes/ajouter'
      preLoaderRoute: typeof CampagnesAjouterRouteImport
      parentRoute: typeof CampagnesRoute
    }
    '/execution/$testId': {
      id: '/execution/$testId'
      path: '/execution/$testId'
      fullPath: '/execution/$testId'
      preLoaderRoute: typeof ExecutionTestIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exigences/ajouter': {
      id: '/exigences/ajouter'
      path: '/ajouter'
      fullPath: '/exigences/ajouter'
      preLoaderRoute: typeof ExigencesAjouterRouteImport
      parentRoute: typeof ExigencesRoute
    }
    '/fonctionnalites/ajouter': {
      id: '/fonctionnalites/ajouter'
      path: '/ajouter'
      fullPath: '/fonctionnalites/ajouter'
      preLoaderRoute: typeof FonctionnalitesAjouterRouteImport
      parentRoute: typeof FonctionnalitesRoute
    }
    '/points-a-surveiller/ajouter': {
      id: '/points-a-surveiller/ajouter'
      path: '/ajouter'
      fullPath: '/points-a-surveiller/ajouter'
      preLoaderRoute: typeof PointsASurveillerAjouterRouteImport
      parentRoute: typeof PointsASurveillerRoute
    }
    '/produits/$productId': {
      id: '/produits/$productId'
      path: '/$productId'
      fullPath: '/produits/$productId'
      preLoaderRoute: typeof ProduitsProductIdRouteImport
      parentRoute: typeof ProduitsRoute
    }
    '/produits/ajouter': {
      id: '/produits/ajouter'
      path: '/ajouter'
      fullPath: '/produits/ajouter'
      preLoaderRoute: typeof ProduitsAjouterRouteImport
      parentRoute: typeof ProduitsRoute
    }
    '/projets/$projectId': {
      id: '/projets/$projectId'
      path: '/$projectId'
      fullPath: '/projets/$projectId'
      preLoaderRoute: typeof ProjetsProjectIdRouteImport
      parentRoute: typeof ProjetsRoute
    }
    '/projets/ajouter': {
      id: '/projets/ajouter'
      path: '/ajouter'
      fullPath: '/projets/ajouter'
      preLoaderRoute: typeof ProjetsAjouterRouteImport
      parentRoute: typeof ProjetsRoute
    }
    '/campagnes/$campaignId/importer': {
      id: '/campagnes/$campaignId/importer'
      path: '/importer'
      fullPath: '/campagnes/$campaignId/importer'
      preLoaderRoute: typeof CampagnesCampaignIdImporterRouteImport
      parentRoute: typeof CampagnesCampaignIdRoute
    }
    '/exigences/$requirementId/modifier': {
      id: '/exigences/$requirementId/modifier'
      path: '/$requirementId/modifier'
      fullPath: '/exigences/$requirementId/modifier'
      preLoaderRoute: typeof ExigencesRequirementIdModifierRouteImport
      parentRoute: typeof ExigencesRoute
    }
    '/fonctionnalites/$featureId/modifier': {
      id: '/fonctionnalites/$featureId/modifier'
      path: '/$featureId/modifier'
      fullPath: '/fonctionnalites/$featureId/modifier'
      preLoaderRoute: typeof FonctionnalitesFeatureIdModifierRouteImport
      parentRoute: typeof FonctionnalitesRoute
    }
    '/produits/$productId/modifier': {
      id: '/produits/$productId/modifier'
      path: '/modifier'
      fullPath: '/produits/$productId/modifier'
      preLoaderRoute: typeof ProduitsProductIdModifierRouteImport
      parentRoute: typeof ProduitsProductIdRoute
    }
    '/projets/$projectId/modifier': {
      id: '/projets/$projectId/modifier'
      path: '/modifier'
      fullPath: '/projets/$projectId/modifier'
      preLoaderRoute: typeof ProjetsProjectIdModifierRouteImport
      parentRoute: typeof ProjetsProjectIdRoute
    }
    '/campagnes/$campaignId/tests/ajouter': {
      id: '/campagnes/$campaignId/tests/ajouter'
      path: '/tests/ajouter'
      fullPath: '/campagnes/$campaignId/tests/ajouter'
      preLoaderRoute: typeof CampagnesCampaignIdTestsAjouterRouteImport
      parentRoute: typeof CampagnesCampaignIdRoute
    }
    '/campagnes/$campaignId/tests/$testId/modifier': {
      id: '/campagnes/$campaignId/tests/$testId/modifier'
      path: '/tests/$testId/modifier'
      fullPath: '/campagnes/$campaignId/tests/$testId/modifier'
      preLoaderRoute: typeof CampagnesCampaignIdTestsTestIdModifierRouteImport
      parentRoute: typeof CampagnesCampaignIdRoute
    }
  }
}

interface AdministrationRouteChildren {
  AdministrationAjouterUtilisateurRoute: typeof AdministrationAjouterUtilisateurRoute
}

const AdministrationRouteChildren: AdministrationRouteChildren = {
  AdministrationAjouterUtilisateurRoute: AdministrationAjouterUtilisateurRoute,
}

const AdministrationRouteWithChildren = AdministrationRoute._addFileChildren(
  AdministrationRouteChildren,
)

interface AnomaliesRouteChildren {
  AnomaliesDefectIdRoute: typeof AnomaliesDefectIdRoute
  AnomaliesAjouterRoute: typeof AnomaliesAjouterRoute
}

const AnomaliesRouteChildren: AnomaliesRouteChildren = {
  AnomaliesDefectIdRoute: AnomaliesDefectIdRoute,
  AnomaliesAjouterRoute: AnomaliesAjouterRoute,
}

const AnomaliesRouteWithChildren = AnomaliesRoute._addFileChildren(
  AnomaliesRouteChildren,
)

interface CampagnesCampaignIdRouteChildren {
  CampagnesCampaignIdImporterRoute: typeof CampagnesCampaignIdImporterRoute
  CampagnesCampaignIdTestsAjouterRoute: typeof CampagnesCampaignIdTestsAjouterRoute
  CampagnesCampaignIdTestsTestIdModifierRoute: typeof CampagnesCampaignIdTestsTestIdModifierRoute
}

const CampagnesCampaignIdRouteChildren: CampagnesCampaignIdRouteChildren = {
  CampagnesCampaignIdImporterRoute: CampagnesCampaignIdImporterRoute,
  CampagnesCampaignIdTestsAjouterRoute: CampagnesCampaignIdTestsAjouterRoute,
  CampagnesCampaignIdTestsTestIdModifierRoute:
    CampagnesCampaignIdTestsTestIdModifierRoute,
}

const CampagnesCampaignIdRouteWithChildren =
  CampagnesCampaignIdRoute._addFileChildren(CampagnesCampaignIdRouteChildren)

interface CampagnesRouteChildren {
  CampagnesCampaignIdRoute: typeof CampagnesCampaignIdRouteWithChildren
  CampagnesAjouterRoute: typeof CampagnesAjouterRoute
}

const CampagnesRouteChildren: CampagnesRouteChildren = {
  CampagnesCampaignIdRoute: CampagnesCampaignIdRouteWithChildren,
  CampagnesAjouterRoute: CampagnesAjouterRoute,
}

const CampagnesRouteWithChildren = CampagnesRoute._addFileChildren(
  CampagnesRouteChildren,
)

interface ExigencesRouteChildren {
  ExigencesAjouterRoute: typeof ExigencesAjouterRoute
  ExigencesRequirementIdModifierRoute: typeof ExigencesRequirementIdModifierRoute
}

const ExigencesRouteChildren: ExigencesRouteChildren = {
  ExigencesAjouterRoute: ExigencesAjouterRoute,
  ExigencesRequirementIdModifierRoute: ExigencesRequirementIdModifierRoute,
}

const ExigencesRouteWithChildren = ExigencesRoute._addFileChildren(
  ExigencesRouteChildren,
)

interface FonctionnalitesRouteChildren {
  FonctionnalitesAjouterRoute: typeof FonctionnalitesAjouterRoute
  FonctionnalitesFeatureIdModifierRoute: typeof FonctionnalitesFeatureIdModifierRoute
}

const FonctionnalitesRouteChildren: FonctionnalitesRouteChildren = {
  FonctionnalitesAjouterRoute: FonctionnalitesAjouterRoute,
  FonctionnalitesFeatureIdModifierRoute: FonctionnalitesFeatureIdModifierRoute,
}

const FonctionnalitesRouteWithChildren = FonctionnalitesRoute._addFileChildren(
  FonctionnalitesRouteChildren,
)

interface PointsASurveillerRouteChildren {
  PointsASurveillerAjouterRoute: typeof PointsASurveillerAjouterRoute
}

const PointsASurveillerRouteChildren: PointsASurveillerRouteChildren = {
  PointsASurveillerAjouterRoute: PointsASurveillerAjouterRoute,
}

const PointsASurveillerRouteWithChildren =
  PointsASurveillerRoute._addFileChildren(PointsASurveillerRouteChildren)

interface ProduitsProductIdRouteChildren {
  ProduitsProductIdModifierRoute: typeof ProduitsProductIdModifierRoute
}

const ProduitsProductIdRouteChildren: ProduitsProductIdRouteChildren = {
  ProduitsProductIdModifierRoute: ProduitsProductIdModifierRoute,
}

const ProduitsProductIdRouteWithChildren =
  ProduitsProductIdRoute._addFileChildren(ProduitsProductIdRouteChildren)

interface ProduitsRouteChildren {
  ProduitsProductIdRoute: typeof ProduitsProductIdRouteWithChildren
  ProduitsAjouterRoute: typeof ProduitsAjouterRoute
}

const ProduitsRouteChildren: ProduitsRouteChildren = {
  ProduitsProductIdRoute: ProduitsProductIdRouteWithChildren,
  ProduitsAjouterRoute: ProduitsAjouterRoute,
}

const ProduitsRouteWithChildren = ProduitsRoute._addFileChildren(
  ProduitsRouteChildren,
)

interface ProjetsProjectIdRouteChildren {
  ProjetsProjectIdModifierRoute: typeof ProjetsProjectIdModifierRoute
}

const ProjetsProjectIdRouteChildren: ProjetsProjectIdRouteChildren = {
  ProjetsProjectIdModifierRoute: ProjetsProjectIdModifierRoute,
}

const ProjetsProjectIdRouteWithChildren =
  ProjetsProjectIdRoute._addFileChildren(ProjetsProjectIdRouteChildren)

interface ProjetsRouteChildren {
  ProjetsProjectIdRoute: typeof ProjetsProjectIdRouteWithChildren
  ProjetsAjouterRoute: typeof ProjetsAjouterRoute
}

const ProjetsRouteChildren: ProjetsRouteChildren = {
  ProjetsProjectIdRoute: ProjetsProjectIdRouteWithChildren,
  ProjetsAjouterRoute: ProjetsAjouterRoute,
}

const ProjetsRouteWithChildren =
  ProjetsRoute._addFileChildren(ProjetsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdministrationRoute: AdministrationRouteWithChildren,
  AlertesRoute: AlertesRoute,
  AnomaliesRoute: AnomaliesRouteWithChildren,
  AuditRoute: AuditRoute,
  CampagnesRoute: CampagnesRouteWithChildren,
  CouvertureRoute: CouvertureRoute,
  DashboardAdminRoute: DashboardAdminRoute,
  DashboardChefRoute: DashboardChefRoute,
  DashboardDeveloppeurRoute: DashboardDeveloppeurRoute,
  DashboardTesteurRoute: DashboardTesteurRoute,
  ExigencesRoute: ExigencesRouteWithChildren,
  FonctionnalitesRoute: FonctionnalitesRouteWithChildren,
  GoLiveRoute: GoLiveRoute,
  LoginRoute: LoginRoute,
  NotificationsRoute: NotificationsRoute,
  PointsASurveillerRoute: PointsASurveillerRouteWithChildren,
  ProduitsRoute: ProduitsRouteWithChildren,
  ProjetsRoute: ProjetsRouteWithChildren,
  ReferentielsRoute: ReferentielsRoute,
  ExecutionTestIdRoute: ExecutionTestIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
